---
- hosts: server1
  become: true
  tasks:

  - name: update repository index on server1
    apt: 
      update_cache: yes
      
  - name: Remove apache2 on server1
    apt:
      name: apache2
      state: absent

  - name: Remove php support for apache on server1
    apt: 
      name: libapache2-mod-php
      state: absent

- hosts: server2
  become: true
  tasks:
  
  - name: update repository index on server2
    apt: 
      update_cache: yes
      
  - name: Remove apache2 on server2
    apt:
      name: apache2
      state: absent

  - name: Remove php support for apache on server2
    apt: 
      name: libapache2-mod-php
      state: absent

- hosts: server3
  become: true
  tasks:
      
  - name: update repository index on server3
    apt: 
      update_cache: yes
      
  - name: Remove apache2 on server3
    apt:
      name: apache2
      state: absent

  - name: Remove php support for apache on server3
    apt: 
      name: libapache2-mod-php
      state: absent
